// tests/build-tool-bundling.test.ts — executable KATs for the bundled-tool
// verify-mode build wiring (owner requirement: `npm run build` truthfully
// bundles the tools). The default build runs the generator in --verify mode
// and fails closed on drift; full regeneration is the explicit --regen-tools
// flag only. Drift target: packages/bundled/sqlite3/PROVENANCE.json — a
// generated file no other test reads.
// @ts-nocheck: subprocess and byte-level fixtures.
import { assert, assertEquals, assertNotEquals, assertStringIncludes } from "jsr:@std/assert@1";

const ROOT = new URL("..", import.meta.url).pathname;
const GENERATOR = `${ROOT}scripts/build-bundled-tool-packages.mjs`;
const DRIFT_TARGET = `${ROOT}packages/bundled/sqlite3/PROVENANCE.json`;
const decoder = new TextDecoder();

function run(cmd, args) {
  const out = new Deno.Command(cmd, { args, cwd: ROOT, stdout: "piped", stderr: "piped" }).outputSync();
  return { code: out.code, stdout: decoder.decode(out.stdout), stderr: decoder.decode(out.stderr) };
}
function verify() {
  return run("node", [GENERATOR, "--verify"]);
}

Deno.test("verify mode: the committed generated tree has zero drift", () => {
  const r = verify();
  assertEquals(r.code, 0, r.stderr);
  assertStringIncludes(r.stdout, "VERIFY OK");
});

Deno.test("drift detection: flipping one generated byte fails verify closed and names the file", () => {
  const original = Deno.readFileSync(DRIFT_TARGET);
  try {
    const mutated = Uint8Array.from(original);
    mutated[0] = mutated[0] ^ 0x01;
    Deno.writeFileSync(DRIFT_TARGET, mutated);
    const r = verify();
    assertNotEquals(r.code, 0, "verify must fail closed on drift");
    assertStringIncludes(r.stderr, "byte-drift: packages/bundled/sqlite3/PROVENANCE.json");
    assertStringIncludes(r.stderr, "--regen-tools");
  } finally {
    Deno.writeFileSync(DRIFT_TARGET, original);
  }
  assertEquals(verify().code, 0, "verify must pass again after restoring the byte");
});

Deno.test("drift detection: an ungenerated file inside a generated tree fails verify closed", () => {
  const stray = `${ROOT}packages/bundled/stray-uncommitted-file.txt`;
  try {
    Deno.writeFileSync(stray, new TextEncoder().encode("not generated\n"));
    const r = verify();
    assertNotEquals(r.code, 0, "verify must fail closed on an ungenerated file");
    assertStringIncludes(r.stderr, "ungenerated file present: packages/bundled/stray-uncommitted-file.txt");
  } finally {
    Deno.removeSync(stray);
  }
  assertEquals(verify().code, 0, "verify must pass again after removing the stray file");
});

Deno.test("regen idempotence: full regeneration reproduces the committed bytes exactly", () => {
  const regen = run("node", [GENERATOR]);
  assertEquals(regen.code, 0, regen.stderr);
  const r = verify();
  assertEquals(r.code, 0, "verify after a full regen must be clean (regen == committed bytes)");
  const regen2 = run("node", [GENERATOR]);
  assertEquals(regen2.code, 0, regen2.stderr);
  assertEquals(verify().code, 0, "second regen must remain clean (idempotent)");
});

Deno.test("flag confinement: unknown build args fail; disabled targets still refuse", () => {
  const bad = run("node", ["build.mjs", "--target=store", "--bogus-flag"]);
  assertNotEquals(bad.code, 0);
  assertStringIncludes(bad.stderr, "usage: node build.mjs [--target=developer|store] [--regen-tools]");
  // developer (debug) is ENABLED (observability workstream) — the enterprise
  // target remains disabled.
  const ent = run("node", ["build.mjs", "--target=enterprise", "--regen-tools"]);
  assertNotEquals(ent.code, 0);
  assertStringIncludes(ent.stderr, "target_enterprise_not_enabled");
});

Deno.test("build wiring: the DEFAULT build fails closed on generated drift (prove verify, not regen, is the default)", () => {
  // If the default were regen, the flipped byte would be silently repaired and
  // the build would succeed; verify-only MUST fail fast and name the drift.
  const original = Deno.readFileSync(DRIFT_TARGET);
  try {
    const mutated = Uint8Array.from(original);
    mutated[0] = mutated[0] ^ 0x01;
    Deno.writeFileSync(DRIFT_TARGET, mutated);
    const r = run("node", ["build.mjs"]);
    assertNotEquals(r.code, 0, "default build must fail closed on generated drift");
    assertStringIncludes(r.stderr + r.stdout, "byte-drift: packages/bundled/sqlite3/PROVENANCE.json");
  } finally {
    Deno.writeFileSync(DRIFT_TARGET, original);
  }
  assertEquals(verify().code, 0);
});
