// tests/generated-bundle-untracked.test.ts — the docs/ gallery bundle is BUILD
// OUTPUT, regenerated by scripts/sync-gallery.mjs on every `npm run build`. It
// must NOT be tracked in git (owner feedback 2026-08-31: "diff-code.bundle.js
// shouldn't be in source control on every build") and it must be ignored so a
// post-build `git status` stays clean.
//
// Falsify by re-adding it: `git add -f docs/diff-core.bundle.js` makes the
// "not tracked" assertion fail; removing `docs/*.bundle.js` from .gitignore
// makes the "is ignored" assertion fail.

import { assert, assertEquals } from "jsr:@std/assert@1";

const ROOT = new URL("../", import.meta.url);
const BUNDLE = "docs/diff-core.bundle.js";

async function git(args: string[]): Promise<{ code: number; stdout: string }> {
  const cmd = new Command("git", {
    args,
    cwd: ROOT,
    stdout: "piped",
    stderr: "null",
  });
  const { code, stdout } = await cmd.output();
  return { code, stdout: new TextDecoder().decode(stdout).trim() };
}
const { Command } = Deno;

Deno.test("generated bundle: docs/diff-core.bundle.js is NOT tracked in git", async () => {
  const { stdout } = await git(["ls-files", BUNDLE]);
  assertEquals(stdout, "", `${BUNDLE} is a build artifact and must not be tracked in git`);
});

Deno.test("generated bundle: docs/*.bundle.js is gitignored", async () => {
  // `git check-ignore <path>` exits 0 and echoes the path when it is ignored.
  const { code, stdout } = await git(["check-ignore", BUNDLE]);
  assert(code === 0 && stdout === BUNDLE, `${BUNDLE} must be gitignored (docs/*.bundle.js)`);
});

Deno.test("generated bundle: no other generated *.bundle.js under docs/ is tracked", async () => {
  const { stdout } = await git(["ls-files", "docs/"]);
  const tracked = stdout.split("\n").filter((f) => /\.bundle\.js$/.test(f));
  assertEquals(tracked, [], `generated bundles must not be tracked under docs/: ${tracked.join(", ")}`);
});
