// xan admission KAT — the patched fork is pure-WASI preview-1 (serial shim),
// and the never-fabricate inputs are honestly recorded. The 12.4MiB binary is
// gitignored (regenerated by build.sh); when present (post-build) its imports
// are asserted, otherwise the sha + provenance are the committed authority.
import { assert, assertEquals } from "jsr:@std/assert@1";
import { readFileSync } from "node:fs";
import { existsSync } from "node:fs";

const BIN = new URL("../docs/plans/rust-lane/xan/binaries/xan.wasm", import.meta.url);

Deno.test("xan: pure WASI preview-1, no threads, default tier (binary if present)", () => {
  if (!existsSync(BIN)) return; // gitignored 12.4MiB binary — build.sh regenerates it
  const bytes = readFileSync(BIN);
  const mod = new WebAssembly.Module(bytes);
  const imports = WebAssembly.Module.imports(mod);
  const modules = [...new Set(imports.map((i) => i.module))];
  assertEquals(modules, ["wasi_snapshot_preview1"], "only WASI preview-1");
  assertEquals(imports.filter((i) => i.kind === "memory").length, 0, "no imported memory");
  assertEquals(imports.filter((i) => i.name.includes("thread") || i.name.includes("atomic")).length, 0, "no thread/atomic imports");
  assert(bytes.length <= 16 * 1024 * 1024, "default tier (≤16MiB)");
});

Deno.test("xan: the never-fabricate inputs are real (sha + commit + licence + shim)", () => {
  const prov = readFileSync(new URL("../docs/plans/rust-lane/xan/PROVENANCE.md", import.meta.url), "utf8");
  assert(prov.includes("d8a1246ccf7c06d02b88656344909a677af58e5fd3d28464800c5815f5d4bd06"), "binary sha256 recorded");
  assert(prov.includes("ae02022bf700b5b414c7481ebf69f207f38314ad"), "source commit pinned");
  assert(prov.includes("MIT OR Unlicense"), "upstream licence recorded");
  assert(prov.includes("rayon-wasi serial shim"), "the serial shim is disclosed");
});

Deno.test("xan: the GPL-family crates are EXCLUDED via permissive stubs (honest NOTICES)", () => {
  const notices = readFileSync(new URL("../docs/plans/rust-lane/xan/xan-NOTICES.txt", import.meta.url), "utf8");
  assert(notices.includes("namedlock-wasi"), "namedlock GPL-2.0+ exclusion stub is documented");
  assert(notices.includes("priority-queue-wasi"), "priority-queue LGPL exclusion stub is documented");
  assert(!/GPL-2\.0\+ \(lock-only; non-wasip1 target\)/.test(notices), "no stale 'lock-only absent' claim");
  const bs = readFileSync(new URL("../docs/plans/rust-lane/xan/build.sh", import.meta.url), "utf8");
  assert(bs.includes("namedlock = { path") && bs.includes("priority-queue = { path"), "build.sh installs all three stubs");
});

Deno.test("xan: the serial rayon shim is committed + is the single unblock for the rayon tools", () => {
  const shim = readFileSync(new URL("../docs/plans/rust-lane/rayon-wasi/src/lib.rs", import.meta.url), "utf8");
  assert(shim.includes("ParallelSliceMut"), "shim provides the parallel slice sorts");
  assert(shim.includes("try_for_each"), "shim provides the parallel iterator");
  assert(shim.includes("ThreadPoolBuilder"), "shim provides the no-op pool builder");
  const readme = readFileSync(new URL("../docs/plans/rust-lane/rayon-wasi/README.md", import.meta.url), "utf8");
  assert(readme.includes("serial"), "the serial semantics are disclosed");
  const bs = readFileSync(new URL("../docs/plans/rust-lane/xan/build.sh", import.meta.url), "utf8");
  assert(bs.includes("rayon = { path"), "build.sh installs the shim via [patch.crates-io]");
});
