// shared/i18n.js — the internationalisation lookup seam
// (chrome-agent-platform-54q, foundation only — no translations ship).
//
// Every user-visible string resolves through `t(key, ...subs)` instead of a
// hardcoded literal. The SINGLE source of truth for message text is
// extension/_locales/en/messages.json (the Chrome MV3 message catalogue);
// the manifest's default_locale points at it.
//
// Resolution order:
//   1. chrome.i18n.getMessage — present in every extension context (pages,
//      service worker, content scripts, workers). Adding a second locale is
//      ONLY a new extension/_locales/<lang>/messages.json catalogue; Chrome
//      selects it from the browser language with ZERO code change.
//   2. The embedded DEFAULT catalogue below — a byte-identical synced copy of
//      _locales/en/messages.json, regenerated by scripts/sync-i18n.mjs. It is
//      the fallback for contexts with no chrome.i18n — chiefly the docs/
//      component gallery, which loads these components from a plain web page
//      and must render IDENTICALLY after migration (the gallery drift guard).
//
// A missing key returns the key itself: a migration gap is loud, never a
// silent blank.

// SYNC:i18n-fallback:start
// Regenerated by scripts/sync-i18n.mjs from extension/_locales/en/messages.json.
export const I18N_DEFAULT_CATALOGUE = Object.freeze({
  "components_copied_exact": "Copied exact artifact content.",
  "components_copied_preview": "Copied preview content (file-backed stream in OPFS).",
  "components_copy_exact_content": "Copy exact content",
  "components_copy_failed_manual": "Copy failed. Select the source and copy it manually.",
  "components_copy_preview_content": "Copy preview content",
  "components_preview_initial_note": "Preview showing initial 64 KiB. Complete file is retained in OPFS stream ($1 bytes).",
  "components_sandbox_preview_opened": "Interactive preview opened in a restricted sandbox.",
  "components_table_preview_opened": "Interactive table preview opened.",
  "options_about": "\n        About",
  "options_about_1": "About",
  "options_access_mode": "Access Mode",
  "options_act": "Act",
  "options_action_policy": "Action policy",
  "options_add_a_site_agent": "Add a Site Agent",
  "options_add_file": "\n              Add file\n            ",
  "options_add_folder": "\n              Add folder\n            ",
  "options_add_rule": "Add rule",
  "options_add_server": "\n            Add server\n          ",
  "options_add_site_agent": "Add Site Agent",
  "options_adding_origins_scopes_control_to_the_listed_sites_": "Adding origins scopes control to the listed sites. To allow every site again, turn the switch off and back on.",
  "options_advanced": "\n        Advanced",
  "options_advanced_1": "Advanced",
  "options_agent": "Agent",
  "options_agent_data_maintenance": "Agent data maintenance",
  "options_agent_scope": "Agent scope",
  "options_agents": "\n        Agents",
  "options_agents_1": "Agents",
  "options_agents_that_may_use_provider_run_tools": "Agents that may use provider-run tools",
  "options_all_agents": "All agents",
  "options_allow_more_origins_one_per_line": "Allow more origins (one per line):",
  "options_allow_the_agent_to_control_the_browser": "Allow the agent to control the browser",
  "options_allowed": "Allowed",
  "options_allowed_origins": "Allowed origins",
  "options_always_ask_recommended": "Always ask (recommended)",
  "options_auto_close_run_tabs": "Auto-close run tabs",
  "options_backup_amp_restore": "Backup &amp; restore",
  "options_board_permissions": "\n        Board permissions",
  "options_board_permissions_1": "Board permissions",
  "options_browser_control": "\n        Browser control",
  "options_browser_control_1": "Browser control",
  "options_by_agent": "By agent",
  "options_by_model": "By model",
  "options_change_shortcuts_in_chrome": "Change shortcuts in Chrome",
  "options_changes_save_automatically": "Changes save automatically.",
  "options_check_what_each_enrolled_site_reports_when_a_tool_": "Check what each enrolled site reports when a tool you expect is missing.",
  "options_choose_verbose_to_see_every_tool_call_start_and_ou": "Choose Verbose to see every tool-call start and outcome in the extension console.",
  "options_chrome": "Chrome ",
  "options_chrome_agent_platform": "Chrome Agent Platform",
  "options_chrome_api": "Chrome API",
  "options_chrome_grants": "Chrome grants ",
  "options_clean_up_leftover_files": "Clean up leftover files…",
  "options_connect_a_remote": "Connect a remote ",
  "options_console": "Console",
  "options_console_logging": "Console logging",
  "options_cost": "Cost:",
  "options_data_memory": "\n        Data & memory",
  "options_data_memory_1": "Data & memory",
  "options_deny_all": "Deny all",
  "options_destructive": "Destructive",
  "options_destructive_actions": "Destructive actions",
  "options_developer_features": "Developer features",
  "options_diagnostics": "Diagnostics",
  "options_diagnostics_logs": "Diagnostics logs",
  "options_event": "Event",
  "options_every_named_agent_and_the_hub_can_post_and_claim_j": "Every named agent and the hub can post and claim jobs on the shared board. A rule blocks one specific edge.",
  "options_every_site_you_allow_keeps_its_own_grant_turn_one_": "Every site you allow keeps its own grant; turn one off without touching the others.",
  "options_export_all_data": "Export all data…",
  "options_factory_reset": "Factory reset",
  "options_file_system_access_api_is_unavailable_in_this_brow": "\n            File System Access API is unavailable in this browser environment\n          ",
  "options_full_detail_in_local_logs": "Full detail in local logs",
  "options_full_release_notes": "Full release notes",
  "options_hooks": "\n        Hooks",
  "options_import": "Import",
  "options_import_a_backup_file": "\n            Import a backup file\n            ",
  "options_import_from_file": "Import from file…",
  "options_keep_every_run_log": "Keep every run log",
  "options_keyboard_shortcuts": "Keyboard shortcuts",
  "options_let_the_hub_hand_parts_of_a_task_to_your_site_agen": "Let the hub hand parts of a task to your Site Agents.",
  "options_loading_shortcuts": "Loading shortcuts…",
  "options_loading_the_changelog": "Loading the changelog…",
  "options_local_folders": "\n        Local folders",
  "options_local_folders_files": "Local folders & files",
  "options_log_verbosity": "Log verbosity",
  "options_mcp_servers": "\n        MCP servers",
  "options_mcp_servers_1": "MCP servers",
  "options_multiple_agents": "Multiple agents",
  "options_never_allow": "Never allow",
  "options_normal": "Normal",
  "options_observability": "Observability",
  "options_off": "Off",
  "options_one_page_says_what_this_extension_sends_what_it_ke": "One page says what this extension sends, what it keeps on this computer, and how to remove it.",
  "options_open_navigate_and_close_tabs_and_capture_screensho": "Open, navigate, and close tabs, and capture screenshots.",
  "options_open_navigate_and_manage_tabs_groups_bookmarks_and": "Open, navigate and manage tabs, groups, bookmarks and page actions. Asks once per site, then runs automatically.",
  "options_open_the_captured_entries_copy_them_for_a_bug_repo": "Open the captured entries, copy them for a bug report, or clear them.",
  "options_permissions": "\n        Permissions",
  "options_permissions_1": "Permissions",
  "options_platform": " Platform",
  "options_privacy": "Privacy",
  "options_provider_server_tools": "Provider server tools",
  "options_providers": "\n        Providers",
  "options_providers_1": "Providers",
  "options_purge_journals": "Purge journals…",
  "options_read": "Read",
  "options_read_only": "Read-only",
  "options_read_page_text_list_tabs_allowed_after_consent_nev": "Read page text, list tabs. Allowed after consent — never interrupts.",
  "options_read_write": "Read/Write",
  "options_reset_all_data": "Reset all data…",
  "options_reusable_capabilities_each_documented_below_a_skil": "\n          Reusable capabilities, each documented below. A skill is included in a\n          task — type ",
  "options_run_logs": "Run logs",
  "options_settings": "Settings",
  "options_settings_chrome_agent_platform": "Settings — Chrome Agent Platform",
  "options_show_detail": "Show detail",
  "options_show_developer_features": "Show developer features",
  "options_site_agent_diagnostics": "Site Agent diagnostics",
  "options_site_origin": "Site origin",
  "options_skills": "\n        Skills",
  "options_skills_1": "Skills",
  "options_system_hooks": "System hooks",
  "options_system_prompts": "System prompts",
  "options_tokens_per_day": "Tokens per day",
  "options_tool_calls": "Tool calls",
  "options_tool_library": "\n        Tool library",
  "options_tool_library_1": "Tool library",
  "options_usage": "\n        Usage",
  "options_usage_1": "Usage",
  "options_verbose": "Verbose",
  "options_version": "Version ",
  "options_what_s_new": "What's new",
  "options_what_the_agent_may_do_once_browser_control_is_on_i": "What the agent may do once Browser control is on, in three classes.",
  "options_what_this_extension_sends_and_stores": "What this extension sends and stores",
  "options_write_a": "Write a ",
});
// SYNC:i18n-fallback:end

/** Apply positional $1..$9 substitutions (chrome.i18n parity for the
 * fallback path; the extension path gets them natively). */
function substitute(message, subs) {
  if (!subs || subs.length === 0) return message;
  return String(message).replace(/\$([1-9])/g, (m, n) => {
    const v = subs[Number(n) - 1];
    return v === undefined || v === null ? m : String(v);
  });
}

/** Resolve a catalogue key to user-visible text.
 * `t("settings_nav_providers")` or `t("origin_turn_off", origin)`. */
export function t(key, ...subs) {
  const args = subs.length === 1 && Array.isArray(subs[0]) ? subs[0] : subs;
  try {
    if (typeof chrome !== "undefined" && chrome?.i18n?.getMessage) {
      const v = chrome.i18n.getMessage(key, args.length ? args : undefined);
      if (v) return v;
    }
  } catch {
    /* fall through to the default catalogue */
  }
  const message = I18N_DEFAULT_CATALOGUE[key];
  if (message === undefined) return key; // loud, never silent
  return args.length ? substitute(message, args) : message;
}

/** Hydrate static HTML: fill `data-i18n` text content and `data-i18n-attr`
 * attributes from the catalogue. Attribute form:
 * `data-i18n-attr="aria-label:key;title:key2"` (attribute:key pairs).
 * Elements keep their English text in the markup as the no-JS fallback; the
 * catalogue value is byte-identical so rendering is unchanged. */
export function hydrateI18n(root = document) {
  if (!root?.querySelectorAll) return;
  for (const el of root.querySelectorAll("[data-i18n]")) {
    const key = el.getAttribute("data-i18n");
    if (key) el.textContent = t(key);
  }
  for (const el of root.querySelectorAll("[data-i18n-attr]")) {
    const spec = el.getAttribute("data-i18n-attr") || "";
    for (const pair of spec.split(";")) {
      const idx = pair.indexOf(":");
      if (idx <= 0) continue;
      const attr = pair.slice(0, idx).trim();
      const key = pair.slice(idx + 1).trim();
      if (attr && key) el.setAttribute(attr, t(key));
    }
  }
}
