// scripts/sync-i18n.mjs — regenerate the embedded DEFAULT catalogue inside
// extension/shared/i18n.js from extension/_locales/en/messages.json.
//
//   node scripts/sync-i18n.mjs          → write the synced catalogue
//   node scripts/sync-i18n.mjs --check  → exit 1 if the embedded copy drifted
//
// The _locales catalogue is the SINGLE source of truth; the embedded copy only
// exists so contexts without chrome.i18n (the docs/ gallery) render the same
// English. Run it as a deterministic pre-commit step alongside sync:gallery.

import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

const ROOT = new URL("..", import.meta.url);
const CATALOGUE = new URL("extension/_locales/en/messages.json", ROOT);
const I18N = new URL("extension/shared/i18n.js", ROOT);
const START = "// SYNC:i18n-fallback:start";
const END = "// SYNC:i18n-fallback:end";

function buildBlock(messages) {
  const entries = Object.keys(messages)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(messages[k]?.message ?? "")},`)
    .join("\n");
  return [
    START,
    "// Regenerated by scripts/sync-i18n.mjs from extension/_locales/en/messages.json.",
    `export const I18N_DEFAULT_CATALOGUE = Object.freeze({\n${entries}\n});`,
    END,
  ].join("\n");
}

async function readCatalogue() {
  const raw = JSON.parse(await readFile(CATALOGUE, "utf8"));
  for (const [k, v] of Object.entries(raw)) {
    if (!v || typeof v.message !== "string") {
      throw new Error(`messages.json entry ${JSON.stringify(k)} lacks a string "message"`);
    }
  }
  return raw;
}

export async function syncI18n({ check = false } = {}) {
  const messages = await readCatalogue();
  const expected = buildBlock(messages);
  const src = await readFile(I18N, "utf8");
  const startIdx = src.indexOf(START);
  const endIdx = src.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error("i18n.js is missing the SYNC:i18n-fallback markers");
  }
  // The existing block spans from START to the END marker (inclusive).
  const prefix = src.slice(0, startIdx);
  const suffix = src.slice(endIdx + END.length);
  const next = prefix + expected + suffix;
  if (check) {
    if (next !== src) {
      console.error("i18n drift: extension/shared/i18n.js is out of sync with _locales/en/messages.json — run `node scripts/sync-i18n.mjs`");
      return false;
    }
    console.log(`i18n in sync (${Object.keys(messages).length} messages)`);
    return true;
  }
  await writeFile(I18N, next);
  console.log(`synced ${Object.keys(messages).length} messages into extension/shared/i18n.js`);
  return true;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const check = process.argv.includes("--check");
  const ok = await syncI18n({ check });
  if (!ok) process.exit(1);
}
